# Generated by Django 3.0.2 on 2020-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('c_id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Course_ID')),
                ('c_name', models.CharField(max_length=20, verbose_name='course_name')),
                ('c_description', models.CharField(max_length=200, verbose_name='course_description')),
                ('c_photo_uri', models.CharField(max_length=200, verbose_name='course_photo_url')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('u_shx_pin', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='user_IDcard_pin')),
                ('u_name', models.CharField(max_length=20, verbose_name='user_name')),
                ('u_sname', models.CharField(max_length=20, verbose_name='user_surname')),
                ('u_phonenumber', models.CharField(max_length=13, verbose_name='user_mobile_phone_number')),
                ('u_birthdate', models.DateField(verbose_name='user_birthdate')),
                ('u_regis_date', models.DateTimeField(verbose_name='users registration date')),
            ],
        ),
    ]
