# Generated by Django 3.0.2 on 2020-03-04 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_regis_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='users registration date'),
        ),
    ]
