# Generated by Django 3.0.2 on 2020-03-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20200316_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_shxs_pin',
            new_name='u_shx_pin',
        ),
    ]
