# Generated by Django 3.0.2 on 2020-03-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20200316_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_chosen_course',
            field=models.CharField(default='No course chosen', max_length=30, verbose_name='The course the user registered for'),
        ),
    ]
