# Generated by Django 3.0.2 on 2020-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20200321_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_chosen_course',
            field=models.CharField(default='No course chosen', max_length=30, verbose_name='The course the user registered for'),
        ),
    ]
