# Generated by Django 3.0.3 on 2020-04-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_auto_20200402_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_chosen_course',
        ),
    ]
