# Generated by Django 3.0.3 on 2020-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0024_user_u_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_course',
            field=models.CharField(choices=[('EN', 'English Level 1'), ('RU', 'Rus dili 1'), ('FR', 'Fransız Dili')], default='RU', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_name',
            field=models.CharField(max_length=20, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=models.CharField(max_length=13, verbose_name='User mobile phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_shx_pin',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='User IDcard pin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_sname',
            field=models.CharField(max_length=20, verbose_name='User surname'),
        ),
    ]
