# Generated by Django 3.0.3 on 2020-04-02 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_auto_20200402_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_birthdate',
            field=models.DateField(verbose_name="User's birthdate"),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_course',
            field=models.CharField(choices=[('EN', 'English Level 1'), ('RU', 'Rus dili 1'), ('FR', 'Fransız Dili')], default='RU', max_length=20, verbose_name="User's course(s)"),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_name',
            field=models.CharField(max_length=20, verbose_name="User's name"),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=models.CharField(max_length=13, verbose_name="User's mobile phone number"),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_regis_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="User's registration date"),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_shx_pin',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name="User's ID card pin"),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_sname',
            field=models.CharField(max_length=20, verbose_name="User's surname"),
        ),
    ]
