# Generated by Django 3.0.3 on 2020-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_auto_20200402_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_course',
            field=models.CharField(choices=[('EN', 'English Level 1'), ('RU', 'Rus dili 1'), ('FR', 'Fransız Dili')], default='Rus dili 1', max_length=20, verbose_name="User's course(s)"),
        ),
    ]
