# Generated by Django 3.0.3 on 2020-04-04 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0028_auto_20200403_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_course',
            field=models.CharField(choices=[('', ''), ('Rus', 'Rus dili 1'), ('Fra', 'Fransız Dili'), ('Eng', 'English Level 1'), ('Alm', 'Alman dili'), ('Isp', 'Ispan dili'), ('EN2', 'Ingilis dili 2.')], default='Rus', max_length=20, verbose_name="User's course(s)"),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,13}$')], verbose_name="User's mobile phone number"),
        ),
    ]
