# Generated by Django 3.0.3 on 2020-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0030_auto_20200404_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=models.CharField(max_length=13, verbose_name="User's mobile phone number"),
        ),
    ]
