# Generated by Django 3.0.3 on 2020-04-04 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0031_auto_20200404_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
