# Generated by Django 3.0.3 on 2020-04-04 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0034_auto_20200404_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}$')]),
        ),
    ]
