# Generated by Django 3.0.3 on 2020-04-04 19:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0035_auto_20200404_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=13),
        ),
    ]
