# Generated by Django 3.0.3 on 2020-04-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0036_auto_20200404_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_phoneprefix',
            field=models.CharField(choices=[('AZE1', '050'), ('AZE2', '051'), ('BAK1', '055'), ('BAK2', '099'), ('NAR1', '070'), ('NAR2', '077')], default='AZE1', max_length=4, verbose_name='Phone prefix '),
        ),
    ]
