# Generated by Django 3.0.3 on 2020-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0043_auto_20200405_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phoneprefix',
            field=models.CharField(choices=[('Aze1', '050'), ('Aze2', '051'), ('Bak1', '055'), ('Bak2', '099'), ('Nar1', '070'), ('Nar2', '077')], default='Nar1', max_length=5, verbose_name='Phone prefix '),
        ),
    ]
