# Generated by Django 3.0.3 on 2020-04-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0045_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
