# Generated by Django 3.0.3 on 2020-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0049_auto_20200405_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=models.CharField(max_length=7, verbose_name='user_mobile_phone_number'),
        ),
    ]
