# Generated by Django 3.0.3 on 2020-04-05 19:55

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0050_auto_20200405_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=models.CharField(max_length=7, validators=[main_page.models.validate_hash], verbose_name='user_mobile_phone_number'),
        ),
    ]
