# Generated by Django 3.0.3 on 2020-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0051_auto_20200405_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_regis_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="User's registration date"),
        ),
    ]
