# Generated by Django 3.0.3 on 2020-04-06 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0052_auto_20200406_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_regis_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="User's registration date"),
        ),
    ]
