# Generated by Django 3.0.3 on 2020-04-08 19:51

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0054_auto_20200406_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_name',
            field=models.CharField(max_length=20, validators=[main_page.models.check_name], verbose_name="User's name"),
        ),
    ]
