# Generated by Django 3.0.3 on 2020-04-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0055_auto_20200408_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_name',
            field=models.CharField(max_length=20, verbose_name="User's name"),
        ),
    ]
