# Generated by Django 3.0.3 on 2020-04-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0056_auto_20200409_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='name',
        ),
    ]
