# Generated by Django 3.0.3 on 2020-04-09 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0057_auto_20200409_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="User's name"),
        ),
    ]
