# Generated by Django 3.0.3 on 2020-04-09 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0060_auto_20200409_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phonenumber',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Mobil nömrə 7 rəqəmli olmalıdır. Məs: 1234567', regex='^\\d{7}$')]),
        ),
    ]
