# Generated by Django 3.0.3 on 2020-04-09 15:03

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0061_auto_20200409_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, validators=[main_page.models.check_name], verbose_name="User's name"),
        ),
    ]
